name: influxdb_client
version: 0.1.0-dev.4
description: A InfluxDB 2.0 API Client Library
homepage: https://github.com/influxdata/influxdb-client-dart

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  archive: ^2.0.13
  http: '>=0.12.0 <0.13.0'
  json_annotation: '>=2.0.0 <4.2.0'
  intl: '^0.16.1'
  meta: '>1.1.8 <1.5.0'
  csv: ^4.1.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  json_serializable: ^3.2.2
  mockito: ^3.0.0
  pedantic: ^1.0.0
  test: ^1.3.0
  collection: ^1.14.13

#  flutter_test:
#    sdk: flutter

